from __future__ import annotations

import random
import sys
import time


for _module_name in list(sys.modules):
    if _module_name == "public_goods" or _module_name.startswith("public_goods."):
        sys.modules.pop(_module_name)

from public_goods.auth import verify_user_password  # noqa: E402
from public_goods.config import (  # noqa: E402
    ADMIN_COOKIE_SECURE,
    AUTH_COOKIE_NAME,
    AUTH_TOKEN_TTL_SECONDS,
    DB_PATH,
    DEFAULT_GROUP_SIZE,
    DEMO_DEFAULT_STUDENT_COUNT,
    DEMO_MAX_STUDENT_COUNT,
    LEGACY_ADMIN_COOKIE_NAME,
    MAX_ACTION_POINTS,
    MAX_GROUP_SIZE,
    MIN_GROUP_SIZE,
    PASSWORD_SCHEME_LEGACY_ADMIN,
    PASSWORD_SCHEME_PBKDF2,
    PHASES,
    PHASE_ROUNDS,
    PUBLIC_BASE_URL,
    SQLITE_BUSY_TIMEOUT_MS,
    TOTAL_EXPERIMENT_ROUNDS,
    USER_ROLE_ADMIN,
    USER_ROLE_TEACHER,
)
from public_goods.db import _run_write_with_retry, db, init_db  # noqa: E402
from public_goods.demo import (  # noqa: E402
    create_demo_class,
    simulate_demo_actions,
    simulate_demo_contributions,
    simulate_demo_current_phase,
    simulate_demo_current_round,
)
from public_goods.experiment import (  # noqa: E402
    _choose_group_sizes,
    advance_round,
    assign_late_joiner,
    close_round,
    compute_results,
    count_computed_rounds,
    ensure_int,
    lock_groups,
    next_round_after_compute,
    open_action_stage,
    open_round,
    phase_for_round,
    phase_round_count_for_session,
)
from public_goods.main import app  # noqa: E402
from public_goods.sessions import (  # noqa: E402
    archive_session_to_admin,
    clear_whitelist,
    create_user,
    delete_session,
    duplicate_session_as_admin,
    duplicate_session_setup_as_admin,
    get_session,
    get_session_by_join_token,
    get_session_for_user,
    get_user_by_id,
    get_user_by_username,
    list_sessions,
    list_students,
    list_teachers,
    parse_whitelist_csv,
    rotate_session_join_token,
    session_counts,
    set_session_title,
    set_user_disabled,
    set_user_password,
    transfer_session_owner,
    upsert_whitelist,
    whitelist_check_or_raise,
    whitelist_template_csv,
)


__all__ = [
    "ADMIN_COOKIE_SECURE",
    "AUTH_COOKIE_NAME",
    "AUTH_TOKEN_TTL_SECONDS",
    "DB_PATH",
    "DEFAULT_GROUP_SIZE",
    "DEMO_DEFAULT_STUDENT_COUNT",
    "DEMO_MAX_STUDENT_COUNT",
    "LEGACY_ADMIN_COOKIE_NAME",
    "MAX_ACTION_POINTS",
    "MAX_GROUP_SIZE",
    "MIN_GROUP_SIZE",
    "PASSWORD_SCHEME_LEGACY_ADMIN",
    "PASSWORD_SCHEME_PBKDF2",
    "PHASES",
    "PHASE_ROUNDS",
    "PUBLIC_BASE_URL",
    "SQLITE_BUSY_TIMEOUT_MS",
    "TOTAL_EXPERIMENT_ROUNDS",
    "USER_ROLE_ADMIN",
    "USER_ROLE_TEACHER",
    "_choose_group_sizes",
    "_run_write_with_retry",
    "advance_round",
    "app",
    "archive_session_to_admin",
    "assign_late_joiner",
    "clear_whitelist",
    "close_round",
    "compute_results",
    "count_computed_rounds",
    "create_demo_class",
    "create_user",
    "db",
    "delete_session",
    "duplicate_session_as_admin",
    "duplicate_session_setup_as_admin",
    "ensure_int",
    "get_session",
    "get_session_by_join_token",
    "get_session_for_user",
    "get_user_by_id",
    "get_user_by_username",
    "init_db",
    "list_sessions",
    "list_students",
    "list_teachers",
    "lock_groups",
    "next_round_after_compute",
    "open_action_stage",
    "open_round",
    "parse_whitelist_csv",
    "phase_for_round",
    "phase_round_count_for_session",
    "random",
    "rotate_session_join_token",
    "session_counts",
    "set_session_title",
    "set_user_disabled",
    "set_user_password",
    "simulate_demo_actions",
    "simulate_demo_contributions",
    "simulate_demo_current_phase",
    "simulate_demo_current_round",
    "time",
    "transfer_session_owner",
    "upsert_whitelist",
    "verify_user_password",
    "whitelist_check_or_raise",
    "whitelist_template_csv",
]
