from __future__ import annotations

from .bootstrap import (
    _backfill_session_join_tokens,
    _backfill_session_owners,
    _ensure_bootstrap_admin,
    _get_admin_user_conn,
)
from .duplication import duplicate_session_as_admin, duplicate_session_setup_as_admin
from .duplication_copy import (
    _copy_whitelist_conn,
    _duplicate_session_conn,
    _duplicate_session_setup_conn,
    _get_source_session_and_admin_conn,
    _insert_admin_owned_session_copy_conn,
)
from .session_queries import get_session, get_session_by_join_token, get_session_for_user, list_sessions
from .session_writes import (
    _validate_session_title,
    archive_session_to_admin,
    create_session_record,
    delete_session,
    rotate_session_join_token,
    set_session_title,
    transfer_session_owner,
)
from .students import get_student_by_public_id, list_students, session_counts, upsert_joined_student
from .users import (
    _create_user_conn,
    _get_teacher_or_404,
    _rehash_legacy_user_password_conn,
    _set_user_password_conn,
    bind_user_external_identity,
    create_microsoft_user,
    create_user,
    get_user_by_email,
    get_user_by_external_identity,
    get_user_by_id,
    get_user_by_username,
    list_teachers,
    remove_teacher_and_reassign_sessions,
    set_user_disabled,
    set_user_password,
)
from .whitelist import (
    clear_whitelist,
    parse_whitelist_csv,
    upsert_whitelist,
    whitelist_check_or_raise,
    whitelist_template_csv,
)


__all__ = [
    "_backfill_session_join_tokens",
    "_backfill_session_owners",
    "_copy_whitelist_conn",
    "_create_user_conn",
    "_duplicate_session_conn",
    "_duplicate_session_setup_conn",
    "_ensure_bootstrap_admin",
    "_get_admin_user_conn",
    "_get_source_session_and_admin_conn",
    "_get_teacher_or_404",
    "_insert_admin_owned_session_copy_conn",
    "_rehash_legacy_user_password_conn",
    "_set_user_password_conn",
    "_validate_session_title",
    "archive_session_to_admin",
    "bind_user_external_identity",
    "clear_whitelist",
    "create_microsoft_user",
    "create_session_record",
    "create_user",
    "delete_session",
    "duplicate_session_as_admin",
    "duplicate_session_setup_as_admin",
    "get_session",
    "get_session_by_join_token",
    "get_session_for_user",
    "get_student_by_public_id",
    "get_user_by_email",
    "get_user_by_external_identity",
    "get_user_by_id",
    "get_user_by_username",
    "list_sessions",
    "list_students",
    "list_teachers",
    "parse_whitelist_csv",
    "remove_teacher_and_reassign_sessions",
    "rotate_session_join_token",
    "session_counts",
    "set_session_title",
    "set_user_disabled",
    "set_user_password",
    "transfer_session_owner",
    "upsert_joined_student",
    "upsert_whitelist",
    "whitelist_check_or_raise",
    "whitelist_template_csv",
]
